export const CONFIG_CATEGORIES = [
  "基础信息",
  "连接与端口",
  "权限与密码",
  "倍率设置",
  "生物与驯养",
  "采集与资源",
  "建筑与 PvP",
  "玩家成长",
  "RCON 与管理",
  "高级参数",
];

export const CONFIG_SCHEMA = [
  {
    file: "GameUserSettings.ini",
    section: "SessionSettings",
    key: "SessionName",
    displayNameZh: "服务器名称",
    descriptionZh: "在服务器浏览器中显示的私服名称。",
    categoryZh: "基础信息",
    type: "string",
    defaultValue: "我的方舟飞升私服",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "ServerPassword",
    displayNameZh: "服务器密码",
    descriptionZh: "玩家加入服务器时需要输入的密码，留空表示公开加入。",
    categoryZh: "权限与密码",
    type: "string",
    defaultValue: "",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "ServerAdminPassword",
    displayNameZh: "管理员密码",
    descriptionZh: "用于启用管理员命令的密码。",
    categoryZh: "权限与密码",
    type: "string",
    defaultValue: "changeme",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "MaxPlayers",
    displayNameZh: "最大玩家数",
    descriptionZh: "允许同时在线的最大玩家数量。",
    categoryZh: "连接与端口",
    type: "number",
    defaultValue: 10,
    min: 1,
    max: 200,
    unitZh: "人",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "ServerPVE",
    displayNameZh: "PVE 模式",
    descriptionZh: "开启后玩家之间不能直接进行 PVP 对抗。",
    categoryZh: "建筑与 PvP",
    type: "boolean",
    defaultValue: true,
    optionLabelsZh: { true: "开启", false: "关闭" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "AllowThirdPersonPlayer",
    displayNameZh: "允许第三人称",
    descriptionZh: "允许玩家使用第三人称视角。",
    categoryZh: "基础信息",
    type: "boolean",
    defaultValue: true,
    optionLabelsZh: { true: "允许", false: "禁止" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "ShowMapPlayerLocation",
    displayNameZh: "地图显示玩家位置",
    descriptionZh: "在地图上显示玩家自己的当前位置。",
    categoryZh: "基础信息",
    type: "boolean",
    defaultValue: true,
    optionLabelsZh: { true: "显示", false: "隐藏" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "DifficultyOffset",
    displayNameZh: "难度偏移",
    descriptionZh: "影响野生生物等级上限的基础难度参数。",
    categoryZh: "高级参数",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 10,
    step: 0.1,
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "OverrideOfficialDifficulty",
    displayNameZh: "官方难度覆盖",
    descriptionZh: "覆盖官方难度值，常用于提升野生生物最高等级。",
    categoryZh: "高级参数",
    type: "number",
    defaultValue: 5,
    min: 0,
    max: 20,
    step: 0.1,
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "XPMultiplier",
    displayNameZh: "经验倍率",
    descriptionZh: "玩家和生物获得经验的倍率。",
    categoryZh: "倍率设置",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 100,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "TamingSpeedMultiplier",
    displayNameZh: "驯养速度倍率",
    descriptionZh: "提高后可加快驯养速度。",
    categoryZh: "生物与驯养",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 100,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "HarvestAmountMultiplier",
    displayNameZh: "采集数量倍率",
    descriptionZh: "每次采集获得资源数量的倍率。",
    categoryZh: "采集与资源",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 100,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "HarvestHealthMultiplier",
    displayNameZh: "资源生命倍率",
    descriptionZh: "资源节点可被采集的耐久倍率。",
    categoryZh: "采集与资源",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 100,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "DayCycleSpeedScale",
    displayNameZh: "昼夜循环速度",
    descriptionZh: "控制完整昼夜循环速度。",
    categoryZh: "倍率设置",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "DayTimeSpeedScale",
    displayNameZh: "白天速度",
    descriptionZh: "控制白天流逝速度。",
    categoryZh: "倍率设置",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "NightTimeSpeedScale",
    displayNameZh: "夜晚速度",
    descriptionZh: "控制夜晚流逝速度。",
    categoryZh: "倍率设置",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "PlayerCharacterWaterDrainMultiplier",
    displayNameZh: "玩家口渴速度",
    descriptionZh: "玩家水分消耗倍率。",
    categoryZh: "玩家成长",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "PlayerCharacterFoodDrainMultiplier",
    displayNameZh: "玩家饥饿速度",
    descriptionZh: "玩家食物消耗倍率。",
    categoryZh: "玩家成长",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "DinoCharacterFoodDrainMultiplier",
    displayNameZh: "恐龙饥饿速度",
    descriptionZh: "恐龙食物消耗倍率，常影响驯养节奏。",
    categoryZh: "生物与驯养",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "AllowFlyerCarryPvE",
    displayNameZh: "PVE 允许飞行生物抓取",
    descriptionZh: "PVE 模式下允许飞行生物抓取目标。",
    categoryZh: "生物与驯养",
    type: "boolean",
    defaultValue: true,
    optionLabelsZh: { true: "允许", false: "禁止" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "DisableStructureDecayPvE",
    displayNameZh: "关闭 PVE 建筑衰减",
    descriptionZh: "开启后 PVE 建筑不会按衰减规则消失。",
    categoryZh: "建筑与 PvP",
    type: "boolean",
    defaultValue: true,
    optionLabelsZh: { true: "关闭衰减", false: "启用衰减" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "PreventDownloadSurvivors",
    displayNameZh: "禁止下载角色",
    descriptionZh: "阻止玩家从其他服务器下载幸存者角色。",
    categoryZh: "权限与密码",
    type: "boolean",
    defaultValue: false,
    optionLabelsZh: { true: "禁止", false: "允许" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "PreventDownloadItems",
    displayNameZh: "禁止下载物品",
    descriptionZh: "阻止玩家从其他服务器下载物品。",
    categoryZh: "权限与密码",
    type: "boolean",
    defaultValue: false,
    optionLabelsZh: { true: "禁止", false: "允许" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "PreventDownloadDinos",
    displayNameZh: "禁止下载生物",
    descriptionZh: "阻止玩家从其他服务器下载生物。",
    categoryZh: "权限与密码",
    type: "boolean",
    defaultValue: false,
    optionLabelsZh: { true: "禁止", false: "允许" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "RCONEnabled",
    displayNameZh: "启用 RCON",
    descriptionZh: "允许通过 RCON 远程管理服务器。",
    categoryZh: "RCON 与管理",
    type: "boolean",
    defaultValue: true,
    optionLabelsZh: { true: "开启", false: "关闭" },
    restartRequired: true,
  },
  {
    file: "GameUserSettings.ini",
    section: "ServerSettings",
    key: "RCONPort",
    displayNameZh: "RCON 端口",
    descriptionZh: "RCON 管理服务监听端口。",
    categoryZh: "RCON 与管理",
    type: "number",
    defaultValue: 27020,
    min: 1,
    max: 65535,
    unitZh: "端口",
    restartRequired: true,
  },
  {
    file: "Game.ini",
    section: "/Script/ShooterGame.ShooterGameMode",
    key: "bAllowUnlimitedRespecs",
    displayNameZh: "允许无限洗点",
    descriptionZh: "允许玩家重复重置属性点。",
    categoryZh: "玩家成长",
    type: "boolean",
    defaultValue: true,
    optionLabelsZh: { true: "允许", false: "禁止" },
    restartRequired: true,
  },
  {
    file: "Game.ini",
    section: "/Script/ShooterGame.ShooterGameMode",
    key: "MatingIntervalMultiplier",
    displayNameZh: "繁殖间隔倍率",
    descriptionZh: "降低可缩短生物再次繁殖等待时间。",
    categoryZh: "生物与驯养",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    step: 0.01,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "Game.ini",
    section: "/Script/ShooterGame.ShooterGameMode",
    key: "EggHatchSpeedMultiplier",
    displayNameZh: "孵化速度倍率",
    descriptionZh: "提高后可加快蛋孵化速度。",
    categoryZh: "生物与驯养",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 100,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
  {
    file: "Game.ini",
    section: "/Script/ShooterGame.ShooterGameMode",
    key: "BabyMatureSpeedMultiplier",
    displayNameZh: "幼崽成长速度倍率",
    descriptionZh: "提高后可加快幼崽成长。",
    categoryZh: "生物与驯养",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 100,
    step: 0.1,
    unitZh: "倍",
    restartRequired: true,
  },
];

export function schemaId(item) {
  return `${item.file}:${item.section}:${item.key}`;
}

export function validateSchema(schema = CONFIG_SCHEMA) {
  const ids = new Set();
  const errors = [];
  for (const item of schema) {
    for (const field of ["file", "section", "key", "displayNameZh", "descriptionZh", "categoryZh", "type"]) {
      if (!item[field]) errors.push(`${item.key || "(未知)"} 缺少 ${field}`);
    }
    if (!["string", "number", "boolean", "enum", "text"].includes(item.type)) {
      errors.push(`${item.key} 类型非法: ${item.type}`);
    }
    if (item.defaultValue === undefined) errors.push(`${item.key} 缺少默认值`);
    const id = schemaId(item);
    if (ids.has(id)) errors.push(`配置项重复: ${id}`);
    ids.add(id);
  }
  return errors;
}

export function findSchemaItem(file, section, key) {
  return CONFIG_SCHEMA.find((item) => item.file === file && item.section === section && item.key === key);
}
